#!/usr/bin/env python
"""Reproduce the initial Random Forest baseline from the early project stage.

This uses the baseline feature matrix generated by scripts/00_download_prepare_clinvar.py:
GeneSymbol multi-hot + ClinVar Type one-hot + Chromosome one-hot.

Note: this is an early random-split baseline and includes GeneSymbol features. It is
kept for historical comparison, not as the final strict evaluation protocol.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.model_selection import train_test_split


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--x", default="data/processed/hearing_loss_X.parquet")
    parser.add_argument("--y", default="data/processed/hearing_loss_y.npy")
    parser.add_argument("--out", default="results/tables/initial_random_forest_baseline.csv")
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    X = pd.read_parquet(args.x)
    y = np.load(args.y).astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=args.seed, stratify=y
    )

    clf = RandomForestClassifier(n_estimators=300, random_state=args.seed, n_jobs=-1)
    clf.fit(X_train, y_train)

    y_pred = clf.predict(X_test)
    y_prob = clf.predict_proba(X_test)[:, 1]
    cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm.ravel()

    row = {
        "Model": "RandomForest initial baseline",
        "AUC": roc_auc_score(y_test, y_prob),
        "Accuracy": accuracy_score(y_test, y_pred),
        "TN": int(tn),
        "FP": int(fp),
        "FN": int(fn),
        "TP": int(tp),
        "n_features": X.shape[1],
        "n_test": len(y_test),
    }
    out = pd.DataFrame([row])
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(args.out, index=False)

    print(out.to_string(index=False))
    print("\nClassification report:")
    print(classification_report(y_test, y_pred, target_names=["Benign(0)", "Pathogenic(1)"]))
    print(f"Saved: {args.out}")


if __name__ == "__main__":
    main()
